title: "Vinyl Record Collection"
description: "Catalog of my vinyl records"
baseurl: ""
url: "https://evankrocker.github.io"
theme: minima
collections:
  albums:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "albums"
    values:
      layout: "album"
plugins:
  - jekyll-feed
