title: "Vinyl Record Collection"
description: "Catalog of my vinyl records"
baseurl: ""
url: "http://evankrocker.github.io/"
collections:
  albums:
    output: true
  artists:
    output: true
bootstrap_cdn: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
