title: My Vinyl Collection
description: A catalog of my vinyl record collection
baseurl: "http://evankrocker.github.io/"
url: ""
collections:
  artists:
    output: true
    permalink: /artists/:path/
